### ISSUE TITLE
Can support Steam Login?

### ISSUE THREAD

**Issue by vaccinevirus** [ETdoFresh/FishyEOS#1]
Can support Steam Login using External Auth, Steam Session Ticket?
Auth Login ExternalType is fixed ExternalCredentialType.Epic

**Comment by ETdoFresh** [comment]
Yes, I want to improve the authentication portion of this plugin. I'll make sure I cover all the cases and post an update here. Thanks for the request.

**Comment by ETdoFresh** [comment]
I added commit: https://github.com/ETdoFresh/FishyEOS/commit/fbf9ed61ecbab8381f5cda5738608dd1dc4d70da

The authentication portion of the plugin now directly forwards these fields to EOS-SDK. I do not have a means to try it out, but this should now work for all the options, including Steam. I will close this issue, but please feel free to open a new issue if you run into more issues along the way. Thanks!
![image](https://user-images.githubusercontent.com/1261843/197363486-cdfad93a-54ee-413a-9087-eb05ad98b166.png)
