### ISSUE TITLE
ServerPeer.GetConnectionAddress() should return the Remote Product User ID and not the Local Product User ID

### ISSUE THREAD

**Issue by bphillips09** [ETdoFresh/FishyEOS#17]
https://github.com/ETdoFresh/FishyEOS/blob/4653c194adfb6a8729365b28e89dbb48e15794f2/FishNet/Plugins/FishyEOS/Core/ServerPeer.cs#L497

This should likely be 
```c#
return client.RemoteUserId.ToString();
```

It should also allow the local host client to call without getting an exception. If you do `NetworkObject.Owner` on something that the host client owns, that function will give an exception since the local host client is not in the `_clients` list.

**Comment by KatoneVi** [comment]
This has been resolved and merged to main.
Close please
