### ISSUE TITLE
How to get started with EOS features (ie: lobbies)

### ISSUE THREAD

**Issue by PixelDough** [ETdoFresh/FishyEOS#2]
I'm struggling to figure out a good way to learn what to do. I looked at the samples for the EOS Plugin, but is there any way to do the same thing with FishyEOS? Or is using the EOS Plugin directly the way to go?

**Comment by ETdoFresh** [comment]
I do plan to add/include a Lobby Sample at some point. But it will most likely be a couple weeks/months down the line. Until then, yes, direct calls to the EOS PlayEveryWare plugin will be your best bet. Here are some references and a bit of sample code to get you started. Good luck! :)

EOS's Lobby Interface API Reference
https://dev.epicgames.com/docs/api-ref/interfaces#lobby-interface

Starter Sample Code... [Create a Lobby](https://dev.epicgames.com/docs/api-ref/functions/eos-lobby-create-lobby)
``` csharp
var options = new CreateLobbyOptions
{
    LocalUserId = EOSManager.Instance?.GetProductUserId(),
    MaxLobbyMembers = 4,
    PermissionLevel = LobbyPermissionLevel.Publicadvertised,
    PresenceEnabled = false,
    AllowInvites = false,
    BucketId = null,
    DisableHostMigration = false,
    EnableRTCRoom = false,
    EnableJoinById = false,
    RejoinAfterKickRequiresInvite = false
};

EOSManager.Instance?.GetEOSLobbyInterface().CreateLobby(ref options, null,
    delegate(ref CreateLobbyCallbackInfo data)
    {
        if (data.ResultCode != Result.Success)
        {
            Debug.LogError("Failed to create lobby");
            return;
        }

        Debug.Log("Created lobby");
    });
```
