### ISSUE TITLE
Can't Connect P2P

### ISSUE THREAD

**Issue by NickMercer** [ETdoFresh/FishyEOS#22]
I updated from an old version of EOS and FishyEOS, and with the new version I can't connect. When I try to connect I get this on the client:

> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0343058-08:00 LogEOSP2P(Verbose): Using Port Range 7777-7876 for P2P traffic
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0343058-08:00 LogEOSP2P(Verbose): InitializeP2PNetwork - Initialized
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0343058-08:00 LogEOSP2P(Verbose): Using Port Range 7777-7876 for P2P traffic
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0353062-08:00 LogEOSP2P(Info): Requesting new TURN relay credentials for 000...21e.
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0408189-08:00 LogEOSP2P(Info): A new connection established listener has been bound. LocalUserId=[000...21e] SocketId=[84696398]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0418165-08:00 LogEOSP2P(Info): A new connection closed listener has been bound. LocalUserId=[000...21e] SocketId=[84696398]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0418165-08:00 LogEOSP2P(Info): Added new peer. LocalUserId=[000...21e] RemoteUserId=[000...be0]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0418165-08:00 LogEOSP2P(Verbose): Queuing signaling message for peer while waiting for turn credentials to be ready. LocalUserId=[000...21e] RemoteUserId=[000...be0] SessionGuid=[KlqowuQjmEab_0_AfNPPEg] MessageId=[0] Type=[com.epicgames.p2p.request_connection] SentTimes=[0/8]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0418165-08:00 LogEOSP2P(Info): Accepted a connection with a peer. LocalUserId=[000...21e] RemoteUserId=[000...be0], SocketId=[84696398]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0428166-08:00 LogEOSP2P(Info): Starting NAT Detection
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.0468194-08:00 LogEOSP2P(Verbose): Sending queued signaling message for peer. LocalUserId=[000...21e] RemoteUserId=[000...be0] MessageId=[0] Type=[com.epicgames.p2p.request_connection]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:42.1416853-08:00 LogEOSP2P(Verbose): Applying updated RTC Configuration
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:46.2106713-08:00 LogEOSP2P(Info): NAT Type was Non-Symmetric
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:47.0500486-08:00 LogEOSP2P(Verbose): Resending signaling message for peer. LocalUserId=[000...21e] RemoteUserId=[000...be0] MessageId=[0] Type=[com.epicgames.p2p.request_connection] SentTimes=[2/8]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:52.1165200-08:00 LogEOSP2P(Verbose): Resending signaling message for peer. LocalUserId=[000...21e] RemoteUserId=[000...be0] MessageId=[0] Type=[com.epicgames.p2p.request_connection] SentTimes=[3/8]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:37:57.1183872-08:00 LogEOSP2P(Verbose): Resending signaling message for peer. LocalUserId=[000...21e] RemoteUserId=[000...be0] MessageId=[0] Type=[com.epicgames.p2p.request_connection] SentTimes=[4/8]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:02.1199257-08:00 LogEOSP2P(Verbose): Resending signaling message for peer. LocalUserId=[000...21e] RemoteUserId=[000...be0] MessageId=[0] Type=[com.epicgames.p2p.request_connection] SentTimes=[5/8]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:07.1218967-08:00 LogEOSP2P(Verbose): Resending signaling message for peer. LocalUserId=[000...21e] RemoteUserId=[000...be0] MessageId=[0] Type=[com.epicgames.p2p.request_connection] SentTimes=[6/8]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:12.1222924-08:00 LogEOSP2P(Verbose): Resending signaling message for peer. LocalUserId=[000...21e] RemoteUserId=[000...be0] MessageId=[0] Type=[com.epicgames.p2p.request_connection] SentTimes=[7/8]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:17.1233202-08:00 LogEOSP2P(Verbose): Resending signaling message for peer. LocalUserId=[000...21e] RemoteUserId=[000...be0] MessageId=[0] Type=[com.epicgames.p2p.request_connection] SentTimes=[8/8]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:17.1233202-08:00 LogEOSP2P(Warning): Reached maximum send attempts for signal message, will not try further. LocalUserId=[000...21e] RemoteUserId=[000...be0] MessageId=[0] Type=[com.epicgames.p2p.request_connection] SentTimes=[8/8]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:27.0456879-08:00 LogEOSP2P(Warning): Removing connection that has timed out. LocalUserId=[000...21e] RemoteUserId=[000...be0] SocketId=[84696398] SessionGuid=[KlqowuQjmEab_0_AfNPPEg]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:27.0456879-08:00 LogEOSP2P(Info): Removed peer with no connections. LocalUserId=[000...21e] RemoteUserId=[000...be0]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:27.0456879-08:00 LogEOSP2P(Info): Connection closed. LocalUserId=[000...21e] RemoteUserId=[000...be0] SocketId=[84696398] Reason=[TimedOut]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:27.0456879-08:00 LogEOSP2P(Verbose): Removing queued packets to/from remote user due connection closing. RemoteUserId=[000...be0] SocketId=[84696398]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:27.0493002-08:00 LogEOSP2P(Info): Successfully closed last connection establish listener for this socket. SocketId=[84696398] NotificationId=[58]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:27.0503011-08:00 LogEOSP2P(Info): Successfully closed last connection closed listener for this socket. LocalUserId=[000...21e] SocketId=[84696398] NotificationId=[59]
> [EOS] [Debug.bindings] [None] [EOS] 2024-03-05T10:38:27.0512947-08:00 LogEOSP2P(Verbose): There were no connections with a peer to close. LocalUserId=[000...21e] RemoteUserId=[000...be0] SocketId=[84696398]

I'm not sure if maybe something needed to be changed with the new EOS SDK 1.16 that the PlayEveryWare plugin has moved to?

I found this on the EOS website, which looks like it could be related, but the proposed fix there didn't do anything:
https://eoshelp.epicgames.com/s/article/Why-are-P2P-connections-failing-with-Dropping-peer-session-signal-message-from-unknown-peer?language=en_US

**Comment by KatoneVi** [comment]
Not sure if you are still experiencing this, but following the instructions:  
https://github.com/ETdoFresh/FishyEOS
1. Getting FishNet into Unity Project
2. PlayEverware eos_plugin_for_unity  and configure it
4. Direct download FishyEOS and threw its Assets folder into my project

It works fine
Please note FishyEOS is built on top of PlayEverware eos_plugin_for_unity, so that's what you should be getting.
I'm using latest version of all 3 and its going nicely.

If anything, let's isolate the issue.
Create a brand new project, and do a fresh implemntation there to see if it works.
I've done it 3 times this week and it works on my end (both PC and Mac)
