### ISSUE TITLE
Invalid Instruction ->  Causing problem with Android Build

### ISSUE THREAD

**Issue by KatoneVi** [ETdoFresh/FishyEOS#26]
This isn't related to your plugin - it works fine
It is your instruction on importing EOS!

Not only should you transfer the "Assets/Plugins/ directory completely over
But you must also trasnfer  "etc/" directory over!
Notice the "etc" directory is located at the ROOT level (meaning, it is a sibling of the Assets directory)

Thanks! :)

**Comment by ETdoFresh** [comment]
Added this post to README :)
