### ISSUE TITLE
Trouble getting android to work with fishyEOS

### ISSUE THREAD

**Issue by LogonDev** [ETdoFresh/FishyEOS#3]
I've been trying to get fishyEOS to work on android the last few days and have had no success 

I set up a brand new projects and did the following steps:

Create a new project using Unity 2021.3.16f1

Downloaded FishNet 3.0.0 Pro

Cloned git clone https://github.com/PlayEveryWare/eos_plugin_for_unity and copied Assets/Plugins into Assets/Plugins

Installed com.unity.editorcoroutines
Also installed com.unity.mobile.android-logcat

Configured the plugin

Openeed FishNet/Example/All/Prediction/CharacterControllerPrediction/CharacterController.Unity
Replaced the transport with FishyEOS
Added this scene to build settings so this is the first scene loaded
Verified this worked in the Unity editor

Followed the instructions for Non-Windows support 
https://github.com/FirstGearGames/FishyEOS

My Android logcat logs when clicking host are as follows

![image](https://user-images.githubusercontent.com/6735429/209781573-11928c11-2bc4-4e5a-b7c6-c94c9934dc3d.png)
![image](https://user-images.githubusercontent.com/6735429/209781602-a5b196a1-4291-4222-9954-1690010b6fc9.png)
![image](https://user-images.githubusercontent.com/6735429/209781619-560cceae-426d-4e99-9f6e-252909238ae4.png)
![image](https://user-images.githubusercontent.com/6735429/209781626-d304d29d-51d3-4a95-91c2-bd036b2f3242.png)

**Comment by ETdoFresh** [comment]
Hey, I'll take a look next week. Will be back from vacation then.

**Comment by alecpizz** [comment]
Any updates on this? Having a similar problem. Beginning to think it's related to PlayEveryware.

**Comment by FirstGearGames** [comment]
Android has been confirmed working as of this time. Please reopen if still an issue.
