### ISSUE TITLE
All clients dropping connection when a single client disconnects

### ISSUE THREAD

**Issue by leoleotte** [ETdoFresh/FishyEOS#8]
When one client disconnects, `EOS_P2P_OnRemoteConnectionClosedCallback` is being called in the server for every client that is connected, causing all of the clients to drop.

Here's the connection IDs when players join:
```
[ServerPeer] Established connection from 0002034f5dc441a6a59dae649d70b514 with handle #Epic.OnlineServices.P2P.SocketId and connection id 1.
[ServerPeer] Established connection from 0002861039944cff8d32791f02b1a585 with handle #Epic.OnlineServices.P2P.SocketId and connection id 2.
[ServerPeer] Established connection from 0002429a57204fe2aa2391d29dc3a5ce with handle #Epic.OnlineServices.P2P.SocketId and connection id 3.
```

And here is what happens when a single client leaves:
```
[ServerPeer] Closed connection from 0002861039944cff8d32791f02b1a585 with handle #Epic.OnlineServices.P2P.SocketId and connection id 1.
[ServerPeer] Closed connection from 0002861039944cff8d32791f02b1a585 with handle #Epic.OnlineServices.P2P.SocketId and connection id 2.
[ServerPeer] Closed connection from 0002861039944cff8d32791f02b1a585 with handle #Epic.OnlineServices.P2P.SocketId and connection id 3.
```

I'm still trying to figure out if this is a problem in FishyEOS, playeverwhere's plugin, the way our lobby is connected or if it's in EOS itself.

**Comment by quentinleon** [comment]
In the same boat here

**Comment by bilck** [comment]
Same here.

**Comment by RoxDevvv** [comment]
oh damn this is so bad i hope dev fix this asap

**Comment by RoxDevvv** [comment]
also, i noticed that when host lost connection OnServerConnectionState and OnRemoteConnectionState and OnClientConnectionState not being called at all

**Comment by FirstGearGames** [comment]
That might be normal for client to not get callbacks when host drops. If host drops suddenly they probably didn't get a chance to send out the packet telling clients it was closing down. There's a new feature though on the Client(and Server)Manager for a timeout independent of transport.

I'm gathering what information I can on this ... stack traces of the server getting the disconnect messages would help a lot.

**Comment by FirstGearGames** [comment]
> When one client disconnects, `EOS_P2P_OnRemoteConnectionClosedCallback` is being called in the server for every client that is connected, causing all of the clients to drop.
> 
> Here's the connection IDs when players join:
> 
> ```
> [ServerPeer] Established connection from 0002034f5dc441a6a59dae649d70b514 with handle #Epic.OnlineServices.P2P.SocketId and connection id 1.
> [ServerPeer] Established connection from 0002861039944cff8d32791f02b1a585 with handle #Epic.OnlineServices.P2P.SocketId and connection id 2.
> [ServerPeer] Established connection from 0002429a57204fe2aa2391d29dc3a5ce with handle #Epic.OnlineServices.P2P.SocketId and connection id 3.
> ```
> 
> And here is what happens when a single client leaves:
> 
> ```
> [ServerPeer] Closed connection from 0002861039944cff8d32791f02b1a585 with handle #Epic.OnlineServices.P2P.SocketId and connection id 1.
> [ServerPeer] Closed connection from 0002861039944cff8d32791f02b1a585 with handle #Epic.OnlineServices.P2P.SocketId and connection id 2.
> [ServerPeer] Closed connection from 0002861039944cff8d32791f02b1a585 with handle #Epic.OnlineServices.P2P.SocketId and connection id 3.
> ```
> 
> I'm still trying to figure out if this is a problem in FishyEOS, playeverwhere's plugin, the way our lobby is connected or if it's in EOS itself.

Any update on your findings? I found the disconnects are being received after an OnTick for playeveryware. This is not necessarily any indicator of a bug as playeveryware is simply polling for updates and the results are received disconnects.

**Comment by ETdoFresh** [comment]
Hey, hmm, interesting… not sure, I should be able to take a look in the next few days.

**Comment by FirstGearGames** [comment]
I've been told by someone that they are starting 3 clients and intentionally disconnecting 1, at which point all drop. I imagine it would work with just 2 clients as well. I BELIEVE one of their clients is host but not sure.

I'm asking for more information and started debugging with them on the FishNet side just in case.

**Comment by FirstGearGames** [comment]
Being told it happens when disconnecting client (not host).

**Comment by bilck** [comment]
I have submitted a PR with a fix for this bug: https://github.com/ETdoFresh/FishyEOS/pull/14

There is still room to improve and more edge cases, but I think this is a good starting point.

**Comment by FirstGearGames** [comment]
Resolved with pr
https://github.com/ETdoFresh/FishyEOS/pull/14
